// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://bvrotpmkazxhyiyohnle.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2cm90cG1rYXp4aHlpeW9obmxlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzczODgyMDEsImV4cCI6MjA5Mjk2NDIwMX0.mzevjc__9yQnX3r8QG-TTVhbIM5SgMTByUkhwWIDugA";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);